# Generated by Django 3.1.1 on 2020-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id_external',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний id компании'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_prod_comp',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='id продукта у поставщика'),
        ),
    ]
